### PR TITLE
Better test running

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
Good point on #2. I revised my branch so that the async-capable version of the `test` function is only loaded in async-capable environments, and only run by the async tests. So in Node 6, the async tests never run, and the old tests all run exactly as they did before; and in Node 7+ harmony, the async tests run and use the different test runner that catches failures. Changing one of the numbers in `arrayEq out, [5, 4, 3]` causes a failure now.

With this approach we don’t need to add any polyfills or shims, and we don’t need to modify any of the old tests. Is there anything I’m missing here? It might help to compare my branch against the `2` branch, you’ll see how little I changed from that eventual merge destination.

### CODE REVIEW

**Comment by GabrielRatener** [comment]
This does appear to work, but it also doesn't run the tests sequentially like the original test-suite did. This is a clever solution but it's also kind of a hack and could lead to problems down the road. Is monkey patching really better than using a helper function?

**Comment by GeoffreyBooth** [comment]
Does it matter that the tests run sequentially? And are you sure they do now? (In the `2` branch, I mean, not your `master`.) There's a comment noting that the tests run out of order.

**Comment by GeoffreyBooth** [comment]
And yes, I think this is better than using the polyfill/shim/helper/whatever you want to call it. I don't want to edit parts of the codebase that don't need editing, like the legacy tests you were changing to get to work with the new test runner.

**Comment by GabrielRatener** [comment]
So your are simply trying to narrow the focus of this PR? That makes sense, but we shouldn't do that at the expense of writing maintainable code. Redefining `test` in one of the test files seems like a bad idea. I think we should have the async `test` function in a separate file that we can import if `async/await` is supported. Maybe

```coffee
if asyncSupported
  global.test = require 'path/to/async-test.coffee'
else
  global.test = (description, fn) ->
    try
      fn.test = {description, currentFile}
      fn.call(fn)
      ++passedTests
    catch e
      failures.push
        filename: currentFile
        error: e
        description: description if description?
        source: fn.toString() if fn.toString?
```

?

**Comment by GeoffreyBooth** [comment]
I thought about that, but the async version of `test` is only used in `test/async.coffee`. The `test` I added there is local to that file; it doesn't overwrite `global.test`. Put a `console.log` in it, you'll see.

You could rename it `testAsync`, and rename all the calls to `test` in that file to `testAsync`, to make it more explicit, but I was trying to keep things standardized with the calls to `test`.

**Comment by GabrielRatener** [comment]
Ok, in the future there will probably be other async features in CS, so it would probably make sense to think more broadly, but I'll leave that for another PR.

**Comment by GeoffreyBooth** [comment]
Agreed. By then hopefully we won't need this harmony nonsense, so it'll be much easier.

**Pull request merged**
